# Generated by Django 3.1.14 on 2022-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordergroup_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='제품 코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='', max_length=100, verbose_name='사이즈'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='is_agreement',
            field=models.BooleanField(default=True, verbose_name='주문 동의'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='payment_type',
            field=models.CharField(choices=[('CARD', '카드'), ('ACCOUNT', '계좌 이체'), ('KAKAO', '카카오 페이')], default='CARD', max_length=100, verbose_name='결제 방법'),
            preserve_default=False,
        ),
    ]
