# Generated by Django 3.1.14 on 2022-07-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0005_auto_20220713_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='deliveries.delivery', verbose_name='배송 정보'),
        ),
    ]
