# Generated by Django 3.1.14 on 2022-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220713_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사이즈'),
        ),
    ]
