# Generated by Django 3.1.14 on 2022-07-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220713_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='payment_price',
            field=models.IntegerField(default=0, verbose_name='결제 금액'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='총 금액'),
        ),
    ]
