# Generated by Django 3.1.14 on 2022-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='예금주'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('KOOKMIN_BANK', '국민은행'), ('WOORI_BANK', '우리은행')], default='KOOKMIN_BANK', max_length=100, verbose_name='은행'),
            preserve_default=False,
        ),
    ]
