# Generated by Django 3.1.14 on 2022-07-11 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecommerce.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
        ('images', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
            bases=(ecommerce.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('release_price', models.IntegerField(verbose_name='출시 가격')),
                ('banner_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='images.image', verbose_name='이미지')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='categories.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상품 모델',
                'verbose_name_plural': '상품 모델',
            },
            bases=(ecommerce.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='options.option', verbose_name='옵션')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 옵션',
                'verbose_name_plural': '상품 옵션',
            },
            bases=(ecommerce.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('code', models.CharField(max_length=100, verbose_name='이름')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='images.image', verbose_name='이미지')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productmodel', verbose_name='상품 모델')),
            ],
            options={
                'verbose_name': '상품 모델 이미지',
                'verbose_name_plural': '상품 모델 이미지',
            },
            bases=(ecommerce.bases.models.UpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productmodel', verbose_name='상품 모델'),
        ),
    ]
