# Generated by Django 3.1.14 on 2022-07-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220711_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodelimage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productmodelimage',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='제품 번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
            preserve_default=False,
        ),
    ]
