# Generated by Django 3.1.14 on 2022-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220712_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='options',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.TextField(blank=True, null=True, verbose_name='재고'),
        ),
    ]
