# Generated by Django 3.1.14 on 2022-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제품 번호'),
        ),
    ]
