# Generated by Django 3.1.14 on 2022-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220712_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='할인율'),
        ),
    ]
