# Generated by Django 3.1.14 on 2022-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220714_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='찜 수'),
        ),
    ]
