# Generated by Django 3.1.14 on 2022-07-12 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20220712_1111'),
        ('likes', '0002_auto_20220711_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodellike',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model_likes', to='products.productmodel', verbose_name='상품 모델'),
        ),
        migrations.AlterField(
            model_name='productmodellike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model_likes', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
