# Generated by Django 3.1.14 on 2022-07-13 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecommerce.apps.deliveries.models
import ecommerce.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('phone', ecommerce.apps.deliveries.models.CustomPhoneNumberField(max_length=20, region=None, verbose_name='전화')),
                ('total_address', models.CharField(max_length=100, verbose_name='주소')),
                ('main_address', models.CharField(max_length=100, verbose_name='메인 주소')),
                ('sub_address', models.CharField(max_length=100, verbose_name='서브 주소')),
                ('postal_code', models.IntegerField(verbose_name='우편 번호')),
                ('delivery_message', models.TextField(blank=True, null=True, verbose_name='배송 메시지')),
                ('status', models.CharField(choices=[('ORDER_COMPLETE', '거래체결'), ('SEND_COMPLETE', '발송완료'), ('DELIVERY_PROCESSING', '배송 중'), ('DELIVERY_COMPLETE', '배송완료')], default='ORDER_COMPLETE', max_length=50, verbose_name='배송 현황')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='users.useraddress', verbose_name='주소지')),
            ],
            options={
                'verbose_name': '주문 그룹 배송 정보',
                'verbose_name_plural': '주문 그룹 배송 정보',
            },
            bases=(ecommerce.bases.models.UpdateMixin, models.Model),
        ),
    ]
