# Generated by Django 3.1.14 on 2022-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_request',
            field=models.TextField(blank=True, null=True, verbose_name='배송 요청 사항'),
        ),
    ]
