# Generated by Django 3.1.14 on 2022-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='point',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='할인 금액'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='이름'),
        ),
    ]
