# Generated by Django 3.1.14 on 2022-07-12 18:21

from django.db import migrations, models
import ecommerce.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220712_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=ecommerce.apps.users.models.CustomPhoneNumberField(default='', max_length=20, region=None, verbose_name='전화'),
            preserve_default=False,
        ),
    ]
