# Generated by Django 3.1.14 on 2022-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='delivery_message',
            field=models.CharField(choices=[('SECURITY_OFFICE', '부재 시 경비실에 맡겨주세요'), ('FRONT_HOUSE', '부재 시 집 앞에 맡겨주세요'), ('DIRECT_INPUT', '직접 입력')], default='SECURITY_OFFICE', max_length=100, verbose_name='배송 메시지'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='delivery_request',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='배송 요청 사항'),
        ),
    ]
