# Generated by Django 3.1.14 on 2022-07-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='products.productmodel', verbose_name='상품 모델'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='options.optiongroup', verbose_name='옵션 그룹'),
        ),
    ]
