# Generated by Django 3.1.14 on 2022-07-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productmodel_quantity'),
        ('options', '0002_auto_20220711_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_groups', to='products.productmodel', verbose_name='상품 모델'),
        ),
    ]
